[package]
name = "userspace-libbpf-ebpf-libbpf"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fork-common = { path = "../fork-common", features=["user"] }
anyhow = "1.0.42"
libbpf-sys = "1.0"
ctrlc = "3.2"

[[bin]]
name = "userspace-libbpf-ebpf-libbpf"
path = "src/main.rs"